### ISSUE TITLE
struct MerkleTree could get #[derive(Debug,  Clone, PartialEq, Eq)] similarly like the Node

### ISSUE THREAD

**Issue by palinko91** [olivmath/merkletreers#2]
It would be handy to have these derives, because I tried to do some other actions after getting the .proof() out of the tree but it consumed by the function and I can't clone the tree now so had to generate a new one to write the code further. Thats why I think a clone function could be handy and also Eq and PartialEq because maybe someone else want to compare MerkleTrees in the future.

**Comment by olivmath** [comment]
Sounds good for me, thanks!
